# permissions for end users to view resourcereloadrestarttriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcereloadrestarttrigger-viewer-role
rules:
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers/status
  verbs:
  - get
