# permissions for end users to edit resourcereloadrestarttriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcereloadrestarttrigger-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: triggered-rollout-restart-operator
    app.kubernetes.io/part-of: triggered-rollout-restart-operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcereloadrestarttrigger-editor-role
rules:
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers/status
  verbs:
  - get
