
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers/finalizers
  verbs:
  - update
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - resourcereloadrestarttriggers/status
  verbs:
  - get
  - patch
  - update
