apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggered-rollout-restart-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - patch
- apiGroups:
  - reload-restart-trigger.k8s.faith
  resources:
  - '*'
  verbs:
  - get
  - list
  - update
  - watch
