kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggered-rollout-restart-operator
subjects:
- kind: ServiceAccount
  name: {{ include "triggered-rollout-restart-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: triggered-rollout-restart-operator
  apiGroup: rbac.authorization.k8s.io
