apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcereloadrestarttriggers.reload-restart-trigger.k8s.faith
spec:
  group: reload-restart-trigger.k8s.faith
  names:
    kind: ResourceReloadRestartTrigger
    listKind: ResourceReloadRestartTriggerList
    plural: resourcereloadrestarttriggers
    singular: resourcereloadrestarttrigger
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ResourceReloadRestartTrigger is the Schema for the resourcereloadrestarttriggers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ResourceReloadRestartTriggerSpec defines the desired state
            of ResourceReloadRestartTrigger
          properties:
            targets:
              description: Targets is a list of targets that will be reloaded when
                triggered
              items:
                properties:
                  kind:
                    description: Kind is the K8s object kind
                    enum:
                    - Deployment
                    - DaemonSet
                    - StatefulSet
                    type: string
                  name:
                    description: Name is the K8s object name
                    type: string
                required:
                - kind
                - name
                type: object
              minItems: 1
              type: array
            triggers:
              description: Secrets is a list of secrets where a change should trigger
                a reload restart
              items:
                properties:
                  kind:
                    description: Kind is the K8s object kind
                    enum:
                    - ConfigMap
                    - Secret
                    type: string
                  name:
                    description: Name is the name of the Secret
                    type: string
                required:
                - kind
                - name
                type: object
              minItems: 1
              type: array
          type: object
        status:
          description: ResourceReloadRestartTriggerStatus defines the observed state
            of ResourceReloadRestartTrigger
          properties:
            targets:
              items:
                properties:
                  kind:
                    description: Kind is the K8s object kind
                    type: string
                  name:
                    description: Name is the K8s object name
                    type: string
                  state:
                    description: State is target state
                    type: string
                  triggers:
                    description: TriggerStatuses is the dependent secrets resourceVersion
                      on the last reload
                    items:
                      properties:
                        kind:
                          description: Kind is the K8s object kind
                          type: string
                        name:
                          description: Name is the K8s Secret name
                          type: string
                        resourceVersion:
                          description: ResourceVersion is the last K8s resourceVersion
                            seen
                          type: string
                        state:
                          description: State is the K8s Secret state
                          type: string
                      required:
                      - kind
                      - name
                      - resourceVersion
                      type: object
                    type: array
                required:
                - kind
                - name
                - state
                - triggers
                type: object
              type: array
            triggers:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  kind:
                    description: Kind is the K8s object kind
                    type: string
                  name:
                    description: Name is the K8s Secret name
                    type: string
                  resourceVersion:
                    description: ResourceVersion is the last K8s resourceVersion seen
                    type: string
                  state:
                    description: State is the K8s Secret state
                    type: string
                required:
                - kind
                - name
                - resourceVersion
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
