kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggered-rollout-restart-operator
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "triggered-rollout-restart-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: triggered-rollout-restart-operator
  apiGroup: rbac.authorization.k8s.io
